In [44]:
import pandas as pd

In [45]:
out = pd.read_excel('output.xlsx')
out = out.iloc[:, :1]
out['Productos'] = out['Productos'].str.capitalize()
out.rename(columns={'Productos': 'Productos Cocina'}, inplace=True)
out['Productos Cocina'] = out['Productos Cocina'].str.replace('Entraña', 'Entrana', case=False)
out

              Productos Cocina
0                     Plateada
1                    Lomo liso
2                       Vetado
3                       Filete
4                      Entrana
5                      Cordero
6           Costillar de cerdo
7             Pollo deshuesado
8                  Cazuela ave
9               Cazuela vacuno
10               Pechuga pollo
11                   Arrollado
12                     Patitas
13                   Longaniza
14  Posta rosada bolsa 1.5 kg.
15             Congrio plancha
16               Congrio frito
17            Congrio caldillo
18                     Reineta
19                     Corvina
20                     Merluza
21                      Salmon
22            Camaron nacional
23                     Calamar
24         Camaron ecuatoriano
25                       Jaiba
26            Machas calientes
27                Machas frias
28                      Ostion
29                      Erizos
30                       Masas
31        Panache verduras 4 ú
32           Quinua 5 unidades
33          Empanadas plateada
34             Empanadas queso
35     Empanadas camaron queso
36                       Locos
37                  Asado tira
38                    Entrecot
39                      Tocino
40                       Huevo
41                       Leche
42            Crema caja 1 lt.
43               Rollo maquina
44                         NaN
45                     Postres
46                        Flan
47                  Panqueques
48      Acaramelado de manzana
49       Torta merengue lúcuma
50    Torta merengue frambuesa
51              Torta 3 leches
52             Torta chocolate
53                 Leche asada
54                 Creme brule
55            Higos en almibar
56             Papayas al jugo
57            Helado chocolate
58             Helado vainilla

In [46]:
df = pd.read_excel('Recetario.xlsx')
df.dropna(inplace=True)
df.rename(columns={'Nombre Producto': 'Producto'}, inplace=True)
# Limpiar espacios en blanco al inicio y final
df['ID'] = df['ID'].astype(str).str.strip()
df['Productos Cocina'] = df['Productos Cocina'].str.strip()

# Luego sigues con tus transformaciones
df['Productos Cocina'] = df['Productos Cocina'].str.replace(r'(?i)\bpatita\b', 'Patitas', regex=True)
df['Productos Cocina'] = df['Productos Cocina'].str.capitalize()
df

          ID                      Producto  Factor          Productos Cocina
0        650                   Acaramelado     1.0               Acaramelado
1    ENT-011  ARRO HUASO P. PALTA Y TOMATE     0.5                 Arrollado
2    CAR-006     ARRO. C/PAPAS COCIDAS PEB     1.0                 Arrollado
3        610    D- ARROLLADO -PAPAS COCIDA     1.0                 Arrollado
4        590       D- SURTIDO CASONA NUEVA     0.5                 Arrollado
..       ...                           ...     ...                       ...
178  POS-016      TORTA MERENGUE FRAMBUESA     1.0  Torta merengue frambuesa
179      530      D-TORTA MERENGUE  LUCUMA     1.0     Torta merengue lucuma
180  POS-015         TORTA MERENGUE LUCUMA     1.0     Torta merengue lucuma
181  PAR-002       BIFE LOMO VETADO 400GRS     1.0                    Vetado
182      540           D- BIFE LOMO VETADO     1.0                    Vetado

[183 rows x 4 columns]

In [ ]:
de = pd.read_csv('export.csv')
de = de[['ID', 'Producto', 'Cantidad']]
de

          ID                        Producto  Cantidad
0    BEB-014    AGUA MINERAL PUYEHUE SIN GAS        19
1    JUG-004         LIMONADA MENTA JENJIBRE        17
2    CAF-001                        ESPRESSO        15
3    BEB-011                  COCA COLA ZERO        13
4    PCC-006               CAZUELA DE VACUNO        12
..       ...                             ...       ...
146  ENT-021  EMPANADAS DE CAMARON-QUESO (2)         1
147  JUG-006            LIMONADA TRADICIONAL         1
148  SOP-001   CONSOME DE PLATEADA CON HUEVO         1
149  ENT-013                  PALTA CARDENAL         1
150  ENS-032                   ENS CAMARONES         1

[151 rows x 3 columns]

In [ ]:
merged = de.merge(df[['ID', 'Productos Cocina', 'Factor']], on='ID', how='left')
merged['VENTA_TOTAL'] = merged['Cantidad'] * merged['Factor']

consumo_agrupado = merged.groupby('Productos Cocina')['VENTA_TOTAL'].sum().reset_index()

inventario_final = out.merge(consumo_agrupado, on='Productos Cocina', how='left').fillna(0)

inventario_final.rename(columns={'VENTA_TOTAL': 'VENTA'}, inplace=True)

inventario_final

              Productos Cocina  VENTA
0                     Plateada   17.0
1                    Lomo liso   17.0
2                       Vetado    3.0
3                       Filete    6.0
4                      Entrana    2.0
5                      Cordero    0.0
6           Costillar de cerdo    1.0
7             Pollo deshuesado    0.0
8                  Cazuela ave    5.5
9               Cazuela vacuno   12.0
10               Pechuga pollo    4.5
11                   Arrollado    1.0
12                     Patitas    0.0
13                   Longaniza    0.0
14  Posta rosada bolsa 1.5 kg.    0.0
15             Congrio plancha    3.0
16               Congrio frito    2.0
17            Congrio caldillo    0.0
18                     Reineta    5.0
19                     Corvina    0.0
20                     Merluza   11.0
21                      Salmon    1.0
22            Camaron nacional    3.5
23                     Calamar    1.0
24         Camaron ecuatoriano   20.0
25                       Jaiba    1.0
26            Machas calientes   15.0
27                Machas frias   72.0
28                      Ostion   23.0
29                      Erizos    7.5
30                       Masas    0.0
31        Panache verduras 4 ú    0.0
32           Quinua 5 unidades    0.0
33          Empanadas plateada   29.0
34             Empanadas queso   31.0
35     Empanadas camaron queso   14.0
36                       Locos   32.0
37                  Asado tira    0.0
38                    Entrecot    0.0
39                      Tocino    0.0
40                       Huevo    0.0
41                       Leche    0.0
42            Crema caja 1 lt.    0.0
43               Rollo maquina    0.0
44                           0    0.0
45                     Postres    0.0
46                        Flan    0.0
47                  Panqueques    0.0
48      Acaramelado de manzana    0.0
49       Torta merengue lúcuma    0.0
50    Torta merengue frambuesa    2.0
51              Torta 3 leches    7.0
52             Torta chocolate    0.0
53                 Leche asada    3.0
54                 Creme brule    0.0
55            Higos en almibar    0.0
56             Papayas al jugo    0.0
57            Helado chocolate    0.0
58             Helado vainilla    0.0

In [49]:
df[df['Productos Cocina'].str.contains('salmon', case=False, na=False)]

          ID                       Producto  Factor Productos Cocina
170  ENT-002       CARPACCIO SALMON AHUMADO     1.0           Salmon
171  ENT-005    CEVICHE CASONA NUEVA SALMON     1.0           Salmon
172  DEL-031          D-SALMON A LA PLANCHA     1.0           Salmon
173     2250  GRAN CEVICHE LA CASONA salmon     1.0           Salmon
174  PES-007            SALMON A LA PLANCHA     1.0           Salmon
175     2260                SALMON IMPERIAL     1.0           Salmon

In [50]:
df[df['Producto'].str.contains('pollo', case=False, na=False)]

           ID                 Producto  Factor  Productos Cocina
145       580  D- ENSALADA CESAR POLLO     1.0     Pechuga pollo
147   DEL-009          D-PECHUGA POLLO     1.0     Pechuga pollo
148   ENS-029         ENS. CESAR POLLO     1.0     Pechuga pollo
149      2840     MEDIA MILANESA POLLO     0.5     Pechuga pollo
150   MEN-003          MENU NIÑO POLLO     0.5     Pechuga pollo
151   CAR-023     MILANESA POLLO DOBLE     1.0     Pechuga pollo
153      1180          POLLO AL AJILLO     1.0     Pechuga pollo
154  PCC-0011           POLLO Al COÑAC     1.0     Pechuga pollo
155   CAR-028          POLLO al PILPIL     1.0     Pechuga pollo
164   PAR-004     1/2 POLLO DESHUEZADO     1.0  Pollo deshuesado